Repository FIXETT/client, pull requests merged in 2023-03, with the labels that each got.

#20 feat: GTM, hotjar 기능 추가
  .env.development
  .env.production
  .gitignore
  package.json
  src/App.tsx
  yarn.lock
Labels: Status: Done, Type: Feature

#27 feat: husky, 자산등록 입력란 삭제 기능 추가
  .env.development
  .env.production
  .eslintcache
  .eslintrc
  .husky/pre-commit
  .husky/pre-push
  package.json
  public/index.html
  src/App.tsx
  src/components/Landing.tsx
  src/components/aside/NavList.tsx
  src/components/map/KaKao.tsx
  src/pages/Fix/FixPage.tsx
  src/pages/Landing/LandingPage.tsx
  src/pages/Signup/ConfirmPage.tsx
  src/pages/Signup/EnterInfoPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/pages/addasset/AddAssetTypeButton.tsx
  src/pages/addasset/AddModal.tsx
  src/pages/addasset/AssetInputList.tsx
  src/pages/addasset/ContextMenu.tsx
  src/pages/addasset/Header.tsx
  src/pages/addasset/InputAsset.tsx
  src/pages/addasset/InputNumber.tsx
  src/pages/addasset/SelectCategory.tsx
  src/pages/addasset/SelectDepartment.tsx
  src/pages/addasset/SelectStatus.tsx
  src/pages/addasset/index.tsx
  src/pages/dashboard/AssetButton.tsx
  src/pages/dashboard/AssetList.tsx
  src/pages/dashboard/AssetRadioButton.tsx
  src/pages/dashboard/DeleteModal.tsx
  src/pages/dashboard/Header.tsx
  src/pages/dashboard/SearchList.tsx
  src/pages/dashboard/index.tsx
  src/pages/modifyasset/ModifyAssetInputList.tsx
  src/pages/modifyasset/ModifyAssetTypeButton.tsx
  src/pages/modifyasset/ModifyAssetTypeList.tsx
  src/pages/modifyasset/ModifyModal.tsx
  src/pages/modifyasset/SelectCategory.tsx
  src/pages/modifyasset/SelectDepartment.tsx
  src/pages/modifyasset/SelectStatus.tsx
  src/pages/modifyasset/index.tsx
  src/recoil/assets.ts
  src/router/Router.tsx
  src/types/asset.ts
  yarn.lock
Labels: Status: In Progress, Type: Feature

#32 [main] feat: 폴더구조 변경 및 견적 요청하기 추가
  src/components/Fix.tsx
  src/components/addasset/AddAssetTypeButton.tsx
  src/components/addasset/AddModal.tsx
  src/components/addasset/AddTableButton.tsx
  src/components/addasset/AssetInputList.tsx
  src/components/addasset/AssetTypeList.tsx
  src/components/addasset/ContextMenu.tsx
  src/components/addasset/Header.tsx
  src/components/addasset/InputAsset.tsx
  src/components/addasset/InputNumber.tsx
  src/components/addasset/SelectCategory.tsx
  src/components/addasset/SelectDepartment.tsx
  src/components/addasset/SelectStatus.tsx
  src/components/aside/NavList.tsx
  src/components/dashboard/AddAssetButton.tsx
  src/components/dashboard/AssetButton.tsx
  src/components/dashboard/AssetList.tsx
  src/components/dashboard/AssetRadioButton.tsx
  src/components/dashboard/AssetTypeList.tsx
  src/components/dashboard/DeleteModal.tsx
  src/components/dashboard/Header.tsx
  src/components/dashboard/SearchList.tsx
  src/components/modifyasset/ModifyAssetInputList.tsx
  src/components/modifyasset/ModifyAssetTypeButton.tsx
  src/components/modifyasset/ModifyAssetTypeList.tsx
  src/components/modifyasset/ModifyModal.tsx
  src/components/modifyasset/SelectCategory.tsx
  src/components/modifyasset/SelectDepartment.tsx
  src/components/modifyasset/SelectStatus.tsx
  src/pages/AddAsset.tsx
  src/pages/Dashboard.tsx
  src/pages/ModifyAsset.tsx
  src/router/Router.tsx
Labels: Status: Done, Type: Feature

#33 style: 반응형 css 수정
  src/components/Layout.tsx
  src/components/addasset/Header.tsx
  src/components/aside/NavList.tsx
  src/pages/AddAsset.tsx
  src/pages/ModifyAsset.tsx
Labels: Status: Done, Type: Improvement

#55 fix: 비밀번호 정규식 대문자 필수 아닌값으로 수정
  src/components/EnterInfo.tsx
  src/components/Landing.tsx
Labels: Status: To do

#57 [main] fix: intercepter 설정 변경
  src/apis/asset.ts
  src/apis/axiosInstance.ts
Labels: Status: Done

#69 fix: 검색페이지 오류 수정
  src/components/dashboard/SearchList.tsx
Labels: Type: Bug, Status: Done

#72 feat: 설문 링크 수정
  src/components/aside/NavList.tsx
Labels: Status: Done

#73 [main] feat: 설문링크 수정
  src/components/aside/NavList.tsx
Labels: Status: Done
